import org1 from "@/assets/organizer-1.jpg";
import org2 from "@/assets/organizer-2.jpg";
import org3 from "@/assets/organizer-3.jpg";
import org4 from "@/assets/organizer-4.jpg";
import org5 from "@/assets/organizer-5.jpg";

export const TOPICS = [
  "Recent Advancement in Advanced Polymers / Materials",
  "Design and Synthesis of Novel Functional Polymers",
  "Polymer Blends and Composites",
  "Polymer Modelling and Simulation",
  "Polymers for Advanced Applications",
  "Membrane Materials for Potable Water and Wastewater Treatment",
  "Functional Membranes for Energy Harvesting and Storage",
  "Conducting Polymers and Electrocatalysts for Water Splitting",
  "Hydrogen Production Technologies",
  "Emerging Materials for Toxicant Removal",
  "Polymeric Biomaterials",
  "Smart Materials",
  "Polymeric Adhesives, Paints and Coatings",
  "Nanomaterials and Composites",
  "Functional Polymers for Biomedical Applications",
  "Materials for Energy Generation and Utilization",
  "Other Allied Fields",
];

export const ORGANIZERS = [
  { role: "Patron", name: "Prof. K. K. Pant", photo: org1, affil: "Director, IIT Roorkee" },
  { role: "Convenor", name: "Prof. S. Chattopadhyay", photo: org2, affil: "IIT Roorkee, Saharanpur" },
  { role: "Co-Convenor", name: "Prof. A. Maiti", photo: org3, affil: "DPPE, IIT Roorkee" },
  { role: "Co-Convenor", name: "Prof. A. Bandyopadhyay", photo: org4, affil: "DPPE, IIT Roorkee" },
  { role: "Organizing Secretary", name: "Prof. V. K. Shahi", photo: org5, affil: "DPPE, IIT Roorkee" },
];

export const SPEAKERS: { name: string; institution: string }[] = [
  { name: "Dr. R. V. Jasra", institution: "Sr. VP, Reliance Industries" },
  { name: "Prof. Diganta Das", institution: "Loughborough University, UK" },
  { name: "Prof. V. Nikonenko", institution: "Kuban State University, Russia" },
  { name: "Prof. P. K. Tewari", institution: "IIT Jodhpur" },
  { name: "Prof. Huacheng Zhang", institution: "RMIT, Melbourne" },
  { name: "Dr. A. K. Pandey", institution: "BARC, Mumbai" },
  { name: "Dr. Y. B. Singh", institution: "KAUST, Saudi Arabia" },
  { name: "Prof. G. Kalon", institution: "IIT Gandhinagar" },
  { name: "Prof. Anshul Yadav", institution: "IIT Roorkee" },
  { name: "Prof. C. N. Murthy", institution: "MSU, Vadodara" },
  { name: "Prof. Roni Kasher", institution: "Ben-Gurion University, Israel" },
  { name: "Dr. U. K. Kharul", institution: "NCL, Pune" },
  { name: "Prof. Shirsendu De", institution: "IIT Kharagpur" },
  { name: "Shri J. Parikh", institution: "Chem. Proc., Ahmedabad" },
  { name: "Prof. P. Kallem", institution: "Abu Dhabi University, UAE" },
  { name: "Dr. Arvind Kumar", institution: "CSIR-CSMCRI, Bhavnagar" },
  { name: "Prof. A. Mudgal", institution: "PDEU, Gandhinagar" },
  { name: "Prof. S. D. Manjare", institution: "BITS, Goa" },
  { name: "Dr. P. K. Labhasetwar", institution: "NEERI, Nagpur" },
  { name: "Dr. J. K. Rathore", institution: "GFL, Gujarat" },
  { name: "Prof. Tushar Jana", institution: "University of Hyderabad" },
  { name: "Dr. Debasish Sarkar", institution: "MNIT, Jaipur" },
  { name: "Dr. K. Selvaraj", institution: "NCL, Pune" },
  { name: "Dr. Vatsala Cilamkoti", institution: "IIT Roorkee" },
  { name: "Prof. G. Arthanareeswaran", institution: "NIT, Trichy" },
  { name: "Prof. Ankur Jain", institution: "GVU, Jaipur" },
  { name: "Prof. Pralay Maiti", institution: "IIT BHU" },
  { name: "Dr. K. Awasthi", institution: "MNIT, Jaipur" },
  { name: "Mr. S. Majumdar", institution: "CSIR-CGCRI, Kolkata" },
  { name: "Prof. Raghuram Chetti", institution: "IIT, Chennai" },
  { name: "Dr. P. K. Sahoo", institution: "NIH Roorkee" },
  { name: "Dr. P. Damaraju", institution: "ONGC, OECT" },
  { name: "Dr. S. Sridhar", institution: "CSIR IICT, Hyderabad" },
  { name: "Dr. B. P. Tripathi", institution: "IIT Delhi" },
  { name: "Dr. P. K. Sahoo", institution: "NIH Roorkee" },
  { name: "Dr. P. K. Prajapati", institution: "Ben-Gurion University, Israel" },
  { name: "Dr. Sankha Karmakar", institution: "IIT, Chennai" },
  { name: "Dr. Bhaskar Deka", institution: "IIT Roorkee" },
  { name: "Dr. Jayabrata Dhar", institution: "NIT, Durgapur" },
  { name: "Prof. Omar Chaalal", institution: "Abu Dhabi University, UAE" },
  { name: "Dr. Razi Epsztein", institution: "Technion, Israel" },
  { name: "Prof. Balram Tripathi", institution: "Rajasthan University, Jaipur" },
  { name: "Prof. M. K. Purkait", institution: "IIT Guwahati" },
  { name: "Prof. A. K. Golder", institution: "IIT Guwahati" },
  { name: "Prof. Ajay Kumar Singh", institution: "IICT Hyderabad" },
  { name: "Prof. Vaibhav Kulshrestha", institution: "CSIR-CSMCRI Bhavnagar" },
  { name: "Dr. Ketan Patel", institution: "CSIR-CSMCRI Bhavnagar" },
  { name: "Dr. R. K. Nagarale", institution: "CSIR-CSMCRI Bhavnagar" },
];

export const COMMITTEES = {
  international: [
    "Prof. Mathias Ulbricht — Germany",
    "Prof. S. K. Jana — USA",
    "Prof. Mark Symes — UK",
    "Prof. Tongwen Xu — China",
    "Prof. Amit Bhatnagar — Finland",
    "Prof. P. Bhattacharya — Sweden",
    "Prof. Andrea Iris Schäfer — Germany",
    "Prof. M. Zhang — Sweden",
    "Prof. Mohtada Sadrzadeh — Canada",
    "Prof. S. H. Moon — South Korea",
    "Prof. Bart V. Bruggen — Belgium",
    "Prof. Bruno Ameduri — France",
  ],
  national: [
    "Dr. R.V. Jasra — Reliance Industries",
    "Prof. T. Pradeep — IIT Madras, Chennai",
    "Prof. Shirsendu De — IIT, Kharagpur",
    "Dr. S. Sridhar — IICT, Hyderabad",
    "Prof. Mihir Kumar Purkait — IIT Guwahati",
    "Prof. Parlay Maiti — IIT-BHU, Varanasi",
    "Dr. P. K. Labhasetwar — NEERI, Nagpur",
    "Prof. Chinmoy Ghorai — IIT Gandhinagar",
    "Prof. G. Arthanareeswaran — NIT Trichi",
    "Prof. Tushar Jana — Univ. of Hyderabad",
  ],
  local: [
    "Prof. Gaurav Manik — IIT Roorkee",
    "Prof. Narayan C. Mishra — IIT Roorkee",
    "Prof. Pradip K. Maji — IIT Roorkee",
    "Prof. Sanjay Palsule — IIT Roorkee",
    "Prof. Bhaskar Deka — IIT Roorkee",
    "Prof. Anshul Yadav — IIT Roorkee",
    "Prof. Udit Choudhury — IIT Roorkee",
    "Prof. Dharmansh — IIT Roorkee",
    "Prof. Kaushik Parida — IIT Roorkee",
    "Prof. Naveen K.R. — IIT Roorkee",
  ],

};
